language: ruby
rvm:
  - 2.1.2
bundler_args: "--without development"
before_install:
  - gem install bundler --pre
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script: bundle exec rspec spec/
