github_repo: https://www.github.com/cyrusstoller/RevTilt
twitter_url: https://www.twitter.com/revtilt

google_analytics:
  development: UA-XXXXXXXX-X
  test: UA-XXXXXXXX-Y
  staging: UA-XXXXXXXX-Z
  production: UA-40427424-1